name: FV62
description: Фото и Видео съемка в Рязани и области
contacts:
  - link: 'tel:+79209522822'
    name: +7920 952 2822
    icon: tel
    description: фото

  - link: 'https://t.me/photovideorzn'
    name: photovideorzn
    icon: telegramm
    description: телеграм канал
    
  - link: 'https://www.instagram.com/photovideorzn'
    name: photovideorzn
    icon: instagram
    description: инстаграм
    

footerText: FV62 - мы стараемся для Вас!
google_analytics: null
theme: null
sass:
  sass_dir: _sass
  style: compressed
collections:
  pages:
    output: false
    permalink: '/:name'
  slideshow:
    output: false
  shop_sku:
    output: true
plugins_dir:
  - jekyll-sass-converter
defaults:
  - values:
      layout: page
