name: FV62
description: Фото и Видео съемка в Рязани и области
contacts:
  - link: 'tel:+79206377000'
    name: +7920 637 7000
    icon: tel
    description: телефон

  - link: 'https://vk.com/fotowed'
    name: vk.com/fotowed
    icon: vkontakte
    description: вконтакте

  - link: 'https://t.me/fotowed'
    name: &#0064;fotowed
    icon: telegramm
    description: телеграм
    
    

footerText: FV62 - мы стараемся для Вас!
google_analytics: null
theme: null
sass:
  sass_dir: _sass
  style: compressed
collections:
  pages:
    output: false
    permalink: '/:name'
  slideshow:
    output: false
  shop_sku:
    output: true
plugins_dir:
  - jekyll-sass-converter
defaults:
  - values:
      layout: page
